# -*- coding: utf-8 -*-
"""DL exp 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ta_UtUFXWxa9irh7dTn79CS2MR67aeU4
"""

import tensorflow as tf

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

from sklearn.metrics import accuracy_score

# ------------------------------------
# Load Dataset
# ------------------------------------

(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Normalize

X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

# One-hot Encoding

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# ------------------------------------
# Build Model
# ------------------------------------

model = Sequential([

    Flatten(input_shape=(28,28)),

    Dense(128, activation="relu"),

    Dense(64, activation="relu"),

    Dense(10, activation="softmax")

])

# ------------------------------------
# Compile
# ------------------------------------

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

# ------------------------------------
# Train
# ------------------------------------

model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

# ------------------------------------
# Evaluate
# ------------------------------------

test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test
)

print(f"\nTest Accuracy: {test_accuracy*100:.2f}%")

# ------------------------------------
# Predict
# ------------------------------------

y_pred = model.predict(X_test)

y_pred_classes = tf.argmax(y_pred, axis=1)

y_true = tf.argmax(y_test, axis=1)

accuracy = accuracy_score(
    y_true,
    y_pred_classes
)

print(f"Accuracy using sklearn: {accuracy*100:.2f}%")