# -*- coding: utf-8 -*-
"""DL exp 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DCdEbM5oaaOBdzevfgRGxQxhC3eA6Qy
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import accuracy_score

# -------------------------------
# Load Dataset
# -------------------------------

iris = load_iris()

X = iris.data
y = iris.target.reshape(-1,1)

# -------------------------------
# One-Hot Encoding
# -------------------------------

encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y)

# -------------------------------
# Train-Test Split
# -------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# -------------------------------
# Standardize Data
# -------------------------------

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -------------------------------
# Network Parameters
# -------------------------------

input_size = X_train.shape[1]
hidden_size = 10
output_size = y_train.shape[1]

learning_rate = 0.01
epochs = 1000

# -------------------------------
# Initialize Weights
# -------------------------------

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# -------------------------------
# Activation Function
# -------------------------------

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# -------------------------------
# Training
# -------------------------------

for epoch in range(epochs):

    # Forward Pass

    z1 = np.dot(X_train, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Loss

    loss = np.mean((a2 - y_train) ** 2)

    # Backpropagation

    d_loss = 2 * (a2 - y_train) / y_train.shape[0]

    d_output = d_loss * sigmoid_derivative(a2)

    dW2 = np.dot(a1.T, d_output)
    db2 = np.sum(d_output, axis=0, keepdims=True)

    d_hidden = np.dot(d_output, W2.T) * sigmoid_derivative(a1)

    dW1 = np.dot(X_train.T, d_hidden)
    db1 = np.sum(d_hidden, axis=0, keepdims=True)

    # Update

    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

# -------------------------------
# Testing
# -------------------------------

z1 = np.dot(X_test, W1) + b1
a1 = sigmoid(z1)

z2 = np.dot(a1, W2) + b2
a2 = sigmoid(z2)

predictions = np.argmax(a2, axis=1)
true_labels = np.argmax(y_test, axis=1)

accuracy = accuracy_score(true_labels, predictions)

print(f"\nAccuracy: {accuracy*100:.2f}%")