# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JaNjbb8wYuQcW9D0YCRuDXBqm1Z0fBQ3
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load and preprocess the text data
def load_text(file_path):
    with open(file_path, 'r') as file:
        text = file.read().lower()
    return text

def prepare_data(text, seq_length):
    tokenizer = Tokenizer(char_level=True)
    tokenizer.fit_on_texts([text])

    total_chars = len(tokenizer.word_index) + 1

    sequences = []
    next_chars = []

    for i in range(0, len(text) - seq_length, 1):
        seq = text[i:i + seq_length]
        label = text[i + seq_length]

        sequences.append([tokenizer.word_index[c] for c in seq])
        next_chars.append(tokenizer.word_index[label])

    X = np.array(sequences)
    y = np.array(next_chars)

    X = pad_sequences(X, maxlen=seq_length) # Ensure all sequences have the same length
    X = to_categorical(X, num_classes=total_chars) # One-hot encode X
    y = to_categorical(y, num_classes=total_chars)

    return X, y, tokenizer, total_chars

def build_model(seq_length, total_chars):
    model = Sequential([
        LSTM(128, input_shape=(seq_length, total_chars), return_sequences=True),
        Dropout(0.2),
        LSTM(128),
        Dense(total_chars, activation='softmax')
    ])

    model.compile(
        loss='categorical_crossentropy',
        optimizer='adam',
        metrics=['accuracy']
    )

    return model

def train_model(model, X, y, epochs=20, batch_size=128):
    model.fit(X, y, epochs=epochs, batch_size=batch_size, verbose=1)

def generate_text(model, tokenizer, total_chars, seed_text, seq_length, num_chars):
    reverse_char_index = tokenizer.index_word

    generated_text = seed_text

    for _ in range(num_chars):
        # Convert seed_text to numerical sequence and then one-hot encode it
        encoded_seed = tokenizer.texts_to_sequences([seed_text])[0]
        x_pred = pad_sequences([encoded_seed], maxlen=seq_length)
        x_pred = to_categorical(x_pred, num_classes=total_chars)

        pred_probs = model.predict(x_pred, verbose=0)[0]
        next_index = np.argmax(pred_probs)
        next_char = reverse_char_index[next_index]

        generated_text += next_char
        seed_text = seed_text[1:] + next_char

    return generated_text

def main():
    text = load_text('/content/sample_data/README.md')

    seq_length = 40

    X, y, tokenizer, total_chars = prepare_data(text, seq_length)

    model = build_model(seq_length, total_chars)

    train_model(model, X, y, epochs=20, batch_size=128)

    seed_text = text[:seq_length]

    generated_text = generate_text(
        model,
        tokenizer,
        total_chars,
        seed_text,
        seq_length,
        num_chars=400
    )

    print(generated_text)

if __name__ == "__main__":
    main()