# -*- coding: utf-8 -*-
"""DL exp 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MjeM-3QzHuzGaZQLCYFJuBaSZ6vajqN9
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

# -------------------------
# Generate Sine Wave
# -------------------------

seq_length = 50
num_samples = 1000

x = np.linspace(0, 100, num_samples)
data = np.sin(x)

# Normalize
scaler = MinMaxScaler()
data = scaler.fit_transform(data.reshape(-1,1))

X = []
y = []

for i in range(len(data)-seq_length):
    X.append(data[i:i+seq_length])
    y.append(data[i+seq_length])

X = np.array(X)
y = np.array(y)

# -------------------------
# Build RNN
# -------------------------

model = Sequential([
    SimpleRNN(
        50,
        activation="relu",
        input_shape=(seq_length,1)
    ),
    Dense(1)
])

model.compile(
    optimizer="adam",
    loss="mse"
)

# -------------------------
# Train
# -------------------------

history = model.fit(
    X,
    y,
    epochs=10,
    batch_size=32
)

# -------------------------
# Predict
# -------------------------

predictions = model.predict(X)

predictions = scaler.inverse_transform(predictions)
y_true = scaler.inverse_transform(y)

# -------------------------
# Plot
# -------------------------

plt.figure(figsize=(12,6))

plt.plot(
    y_true,
    label="True Values"
)

plt.plot(
    predictions,
    label="Predicted Values"
)

plt.title("True vs Predicted Values")

plt.xlabel("Sample Index")

plt.ylabel("Value")

plt.legend()

plt.show()