# -*- coding: utf-8 -*-
"""DL exp 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPaelLkZXdfO5aDpwqxoLSuiKcNG6Gsa
"""

import tensorflow as tf

from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping

# -----------------------------
# Load Dataset
# -----------------------------

(X_train, y_train), (X_test, y_test) = cifar10.load_data()

X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

y_train = to_categorical(y_train,10)
y_test = to_categorical(y_test,10)

# -----------------------------
# CNN Function
# -----------------------------

def build_model(filter_size, stride, padding):

    model = Sequential([

        Conv2D(
            32,
            kernel_size=filter_size,
            strides=stride,
            padding=padding,
            activation="relu",
            input_shape=(32,32,3)
        ),

        MaxPooling2D((2,2)),

        Conv2D(
            64,
            kernel_size=filter_size,
            strides=stride,
            padding=padding,
            activation="relu"
        ),

        MaxPooling2D((2,2)),

        Conv2D(
            128,
            kernel_size=filter_size,
            strides=stride,
            padding=padding,
            activation="relu"
        ),

        Flatten(),

        Dense(128,activation="relu"),

        Dense(10,activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

# -----------------------------
# Experiment
# -----------------------------

filter_sizes=[(3,3),(5,5)]
strides=[(1,1),(2,2)]
paddings=["valid","same"]

for filter_size in filter_sizes:

    for stride in strides:

        for padding in paddings:

            print("\n--------------------------------------")
            print("Filter Size:",filter_size)
            print("Stride:",stride)
            print("Padding:",padding)

            model=build_model(
                filter_size,
                stride,
                padding
            )

            early_stop=EarlyStopping(
                monitor="val_loss",
                patience=3,
                restore_best_weights=True
            )

            model.fit(
                X_train,
                y_train,
                epochs=10,
                batch_size=64,
                validation_split=0.2,
                callbacks=[early_stop],
                verbose=1
            )

            loss,accuracy=model.evaluate(
                X_test,
                y_test,
                verbose=0
            )

            print(f"Test Accuracy: {accuracy*100:.2f}%")